We begin by setting up a C development environment in Linux.

If you haven't installed Linux, please do so now.

After installing Linux we need to appropriate tools to be able to write, compile
and run C programs. Please, in a terminal window execute the following:

#+BEGIN_SRC sh
sudo apt update
sudo apt install git build-essential
#+END_SRC

We also need the CS50 beginners library. A library is a collection of function
someone else (or ourselves) have already programmed that we can reuse in our
programs. We are going to download such a library with a set of useful beginner
friendly functions to ease our introduction to C. Please, run the following
commands in a terminal window:

#+BEGIN_SRC sh
curl -s https://packagecloud.io/install/repositories/cs50/repo/script.deb.sh | sudo bash
sudo apt-get install libcs50
#+END_SRC

To use the library you need to include it as
#+BEGIN_SRC C
#include <cs50.h>
#+END_SRC

And link it with ~-lcs50~. A nice reference list of the functions included with
~cs50.h~ (and many more functions of the C standard library) can be found at
https://reference.cs50.net/.

That is all, happy coding!
